name: echo ENV

on: 
  push:

jobs:
  sample_job:
    runs-on: ubuntu-latest
    steps:
      - id: 'echo_test'
        name: 'echo test'
        run: echo 'TEST'
      - id: variable_test
        name: 'variable test'
        run: VAL="VAL_TEST" && echo $VAL
      - id: get_branch_name
        name: get branch name
        run: VAL=${BRANCH_NAME} && echo $VAL