name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: yarn install
      - uses: actions/setup-node@v3
        with:
          - node-version: 16
          - args: "install"

      - name: yarn lint
        uses: nuxt/actions-yarn@node-11
        with:
          args: "lint"